/** A&D film catalog — ported from the Grok wrap studio. */
export const FILMS = [
  {
    id: 'stainless',
    name: 'Bare Stainless',
    blurb: 'Unwrapped 30X cold-rolled steel. Fingerprints included.',
    category: 'oem',
    color: '#c8ccd1',
    finish: 'metallic',
    lockFinish: true,
    metalness: 0.96,
    roughness: 0.26,
    film: 'None',
    filmMultiplier: 0,
    featured: 'stainless.jpg',
  },
  {
    id: 'destiny',
    name: 'Destiny',
    blurb: 'For Destiny Davis. Blush pearl and a few hearts, sized for her Model 3 phone key.',
    category: 'hers',
    color: '#f3c1cf',
    finish: 'satin',
    lockFinish: true,
    metalness: 0.16,
    roughness: 0.38,
    pattern: 'hearts',
    film: 'A&D · Destiny Davis',
    filmMultiplier: 1.24,
  },
  {
    id: 'ballet',
    name: 'Ballet',
    blurb: 'Slipper pink satin. Soft in the shade, bright on the phone key.',
    category: 'hers',
    color: '#f6d5df',
    finish: 'satin',
    metalness: 0.12,
    roughness: 0.4,
    film: 'Satin ballet pink',
    filmMultiplier: 1.12,
  },
  {
    id: 'cherry',
    name: 'Cherry',
    blurb: 'Gloss cherry. A small car reads like jewelry.',
    category: 'hers',
    color: '#c43b55',
    finish: 'gloss',
    metalness: 0.28,
    roughness: 0.14,
    film: 'Gloss cherry',
    filmMultiplier: 1.16,
  },
  {
    id: 'lilac',
    name: 'Lilac Hour',
    blurb: 'Cool lilac satin. Evening color, not a candy coat.',
    category: 'hers',
    color: '#c9b6dc',
    finish: 'satin',
    metalness: 0.18,
    roughness: 0.4,
    film: 'Satin lilac',
    filmMultiplier: 1.14,
  },
  {
    id: 'rose',
    name: 'Rose Metal',
    blurb: 'Rose gold metal. Catches the light on the door and the key screen.',
    category: 'hers',
    color: '#c48b9a',
    finish: 'metallic',
    metalness: 0.62,
    roughness: 0.28,
    film: 'Rose metal',
    filmMultiplier: 1.22,
  },
  {
    id: 'sakura',
    name: 'Sakura',
    blurb: 'Pale blossom scatter on blush. The girl-side print.',
    category: 'hers',
    color: '#f7d5e0',
    finish: 'satin',
    lockFinish: true,
    metalness: 0.12,
    roughness: 0.4,
    pattern: 'blossom',
    film: 'Printed blossom',
    filmMultiplier: 1.28,
  },
  {
    id: 'butter',
    name: 'Buttercream',
    blurb: 'Warm cream satin. Quiet next to the pinks.',
    category: 'hers',
    color: '#f3e2b8',
    finish: 'satin',
    metalness: 0.14,
    roughness: 0.42,
    film: 'Satin buttercream',
    filmMultiplier: 1.12,
  },
  {
    id: 'cosmic',
    name: 'Cosmic Burst',
    blurb: 'Official Tesla example. The body takes the print; the glass stays glass.',
    category: 'signature',
    color: '#1c3148',
    finish: 'gloss',
    lockFinish: true,
    metalness: 0.35,
    roughness: 0.28,
    pattern: 'stars',
    film: 'Tesla example',
    filmMultiplier: 1,
    trending: true,
    official: '/official/Cosmic_Burst.png',
  },
  {
    id: 'digi',
    name: 'Digital Stealth',
    blurb: 'Official Tesla digital camo. Blocks, not a photo filter.',
    category: 'tactical',
    color: '#3a4038',
    finish: 'matte',
    lockFinish: true,
    metalness: 0.08,
    roughness: 0.7,
    pattern: 'camo',
    film: 'Tesla example',
    filmMultiplier: 1,
    official: '/official/Digital_Camo_Stealth.png',
  },
  {
    id: 'camostealth',
    name: 'Camo Stealth',
    blurb: 'Official Tesla camo print for the flat panels.',
    category: 'tactical',
    color: '#6a685c',
    finish: 'matte',
    lockFinish: true,
    metalness: 0.08,
    roughness: 0.68,
    pattern: 'camo',
    film: 'Tesla example',
    filmMultiplier: 1,
    official: '/official/Camo_Stealth.png',
  },
  {
    id: 'gradblack',
    name: 'Gradient Black',
    blurb: 'Official Tesla gradient. Dark at the nose, lighter through the sail.',
    category: 'graphic',
    color: '#141414',
    finish: 'gloss',
    lockFinish: true,
    metalness: 0.3,
    roughness: 0.22,
    film: 'Tesla example',
    filmMultiplier: 1,
    official: '/official/Gradient_Black.png',
  },
  {
    id: 'void',
    name: 'Deep Void',
    blurb: 'Night sky stretched over the facets. Stars stay put when the steel moves.',
    category: 'signature',
    color: '#0c1016',
    finish: 'satin',
    lockFinish: true,
    metalness: 0.22,
    roughness: 0.38,
    pattern: 'stars',
    film: 'Printed satin · night field',
    filmMultiplier: 1.32,
    featured: 'void.jpg',
    trending: true,
  },
  {
    id: 'lunar',
    name: 'Lunar Dust',
    blurb: 'Pale regolith gray. Quiet in the cabin, bright in the sun.',
    category: 'essentials',
    color: '#c4c0b4',
    finish: 'satin',
    metalness: 0.16,
    roughness: 0.42,
    film: 'Satin lunar gray',
    filmMultiplier: 1.12,
    featured: 'lunar.jpg',
    trending: true,
  },
  {
    id: 'nebula',
    name: 'Cold Nebula',
    blurb: 'Ink and ice dust. The print reads as distance, not a sticker.',
    category: 'signature',
    color: '#141c28',
    finish: 'satin',
    lockFinish: true,
    metalness: 0.2,
    roughness: 0.4,
    pattern: 'nebula',
    film: 'Printed satin · ice dust',
    filmMultiplier: 1.36,
    featured: 'void.jpg',
  },
  {
    id: 'stealth',
    name: 'Stealth Satin',
    blurb: 'The most-installed 2026 film. Kills fingerprints, doubles the geometry.',
    category: 'essentials',
    color: '#141414',
    finish: 'satin',
    metalness: 0.18,
    roughness: 0.42,
    film: '3M 2080 Satin Black',
    filmMultiplier: 1.08,
    featured: 'stealth.jpg',
    trending: true,
  },
  {
    id: 'frozen',
    name: 'Frozen Gray',
    blurb: 'Stealth without the black. Softens oil-canning on the big facets.',
    category: 'essentials',
    color: '#6d7076',
    finish: 'satin',
    metalness: 0.22,
    roughness: 0.4,
    film: 'Avery Supreme Frozen Grey',
    filmMultiplier: 1.1,
    featured: 'frozen.jpg',
  },
  {
    id: 'whiteout',
    name: 'Satin White',
    blurb: 'Quiet, architectural, photographs like folded paper.',
    category: 'essentials',
    color: '#e6e4de',
    finish: 'satin',
    metalness: 0.12,
    roughness: 0.38,
    film: 'Inozetek Super Satin White',
    filmMultiplier: 1.12,
    featured: 'whiteout.jpg',
  },
  {
    id: 'khaki',
    name: 'Desert Khaki',
    blurb: 'The enthusiast signature. Sand-cast planes, desert light.',
    category: 'essentials',
    color: '#b7a48a',
    finish: 'satin',
    metalness: 0.2,
    roughness: 0.44,
    film: 'KPMF Satin Khaki',
    filmMultiplier: 1.14,
    featured: 'khaki.jpg',
    trending: true,
  },
  {
    id: 'champagne',
    name: 'Foundry Champagne',
    blurb: 'Polarizing on purpose. Flat planes catch sun like sheet metal.',
    category: 'essentials',
    color: '#c4b08a',
    finish: 'satin',
    metalness: 0.45,
    roughness: 0.32,
    film: 'Hexis Satin Champagne',
    filmMultiplier: 1.18,
    featured: 'champagne.jpg',
  },
  {
    id: 'olive',
    name: 'Field Olive',
    blurb: 'Matte military green. Tactical without the print.',
    category: 'tactical',
    color: '#3d4634',
    finish: 'matte',
    metalness: 0.08,
    roughness: 0.78,
    film: '3M 2080 Matte Military Green',
    filmMultiplier: 1.12,
    featured: 'olive.jpg',
  },
  {
    id: 'navy',
    name: 'Ink Navy',
    blurb: 'Near-black until the sun hits. Then it reads as deep ink.',
    category: 'essentials',
    color: '#12151c',
    finish: 'satin',
    metalness: 0.28,
    roughness: 0.36,
    film: 'Avery Satin Dark Navy',
    filmMultiplier: 1.1,
    featured: 'navy.jpg',
  },
  {
    id: 'midnight',
    name: 'Midnight Blue',
    blurb: 'Gloss that plays reflections across the facets.',
    category: 'essentials',
    color: '#0c1a33',
    finish: 'gloss',
    metalness: 0.22,
    roughness: 0.12,
    film: 'Inozetek Super Gloss Midnight',
    filmMultiplier: 1.16,
    featured: 'midnight.jpg',
  },
  {
    id: 'gunmetal',
    name: 'Gunmetal',
    blurb: 'Cool industrial gray. The quiet sibling of Stealth.',
    category: 'essentials',
    color: '#3a3d42',
    finish: 'satin',
    metalness: 0.35,
    roughness: 0.36,
    film: '3M 2080 Satin Dark Gray',
    filmMultiplier: 1.1,
    featured: 'gunmetal.jpg',
  },
  {
    id: 'crimson',
    name: 'Crimson Rift',
    blurb: 'Deep wine gloss. Reads black until the sun finds it.',
    category: 'graphic',
    color: '#6b1018',
    finish: 'gloss',
    metalness: 0.24,
    roughness: 0.14,
    film: 'Avery Gloss Carmine Red',
    filmMultiplier: 1.18,
    featured: 'crimson.jpg',
  },
  {
    id: 'shift',
    name: 'Ion Shift',
    blurb: 'Color-shift film. Angle changes teal to violet.',
    category: 'signature',
    color: '#163a38',
    finish: 'shift',
    lockFinish: true,
    metalness: 0.55,
    roughness: 0.18,
    pattern: 'shift',
    film: 'KPMF ColorShift Ion',
    filmMultiplier: 1.4,
    featured: 'shift.jpg',
    trending: true,
  },
  {
    id: 'camo',
    name: 'Tactical Camo',
    blurb: 'Printed desert/olive camo for the flat panels.',
    category: 'tactical',
    color: '#c4c0b4',
    finish: 'matte',
    lockFinish: true,
    metalness: 0.06,
    roughness: 0.72,
    pattern: 'camo',
    film: 'Printed cast vinyl · 3M IJ180',
    filmMultiplier: 1.25,
    featured: 'camo.jpg',
  },
  {
    id: 'topo',
    name: 'Topo Black',
    blurb: 'Contour lines on a dark field. Map energy without stickers.',
    category: 'graphic',
    color: '#d8d4cc',
    finish: 'satin',
    lockFinish: true,
    metalness: 0.14,
    roughness: 0.4,
    pattern: 'topo',
    film: 'Printed satin · Avery Supreme',
    filmMultiplier: 1.28,
    featured: 'topo.jpg',
  },
  {
    id: 'carbon',
    name: 'Dry Carbon',
    blurb: '4D carbon weave. Fake until the light moves.',
    category: 'signature',
    color: '#9a9aa0',
    finish: 'gloss',
    lockFinish: true,
    metalness: 0.4,
    roughness: 0.22,
    pattern: 'carbon',
    film: '4D carbon vinyl · Hexis',
    filmMultiplier: 1.35,
    featured: 'carbon.jpg',
  },
  {
    id: 'livery',
    name: 'Redline Livery',
    blurb: 'Dark body, red slash, race numbers. Phone-key ready.',
    category: 'graphic',
    color: '#161616',
    finish: 'gloss',
    lockFinish: true,
    metalness: 0.2,
    roughness: 0.16,
    pattern: 'livery',
    film: 'Printed gloss · 3M 2080',
    filmMultiplier: 1.3,
    featured: 'livery.jpg',
  },
  {
    id: 'glacier',
    name: 'Glacier',
    blurb: 'Cool satin blue. Softens the Cybertruck’s hard lines.',
    category: 'essentials',
    color: '#8eafc2',
    finish: 'satin',
    metalness: 0.18,
    roughness: 0.4,
    film: 'Avery Satin Light Blue',
    filmMultiplier: 1.12,
  },
  {
    id: 'copper',
    name: 'Forge Copper',
    blurb: 'Warm metal without chrome. Looks poured, not sprayed.',
    category: 'essentials',
    color: '#8a4e32',
    finish: 'metallic',
    metalness: 0.7,
    roughness: 0.28,
    film: 'Hexis Satin Copper',
    filmMultiplier: 1.22,
  },
  {
    id: 'solar',
    name: 'Solar Amber',
    blurb: 'Hot orange gloss. The opposite of Stealth.',
    category: 'essentials',
    color: '#c45112',
    finish: 'gloss',
    metalness: 0.2,
    roughness: 0.14,
    film: '3M 2080 Gloss Fiery Orange',
    filmMultiplier: 1.16,
  },
  {
    id: 'slate',
    name: 'Slate Blue',
    blurb: 'Muted blue-gray satin. Works in any lot.',
    category: 'essentials',
    color: '#3c4d5e',
    finish: 'satin',
    metalness: 0.22,
    roughness: 0.4,
    film: 'KPMF Satin Slate',
    filmMultiplier: 1.1,
  },
  {
    id: 'dune',
    name: 'Dune',
    blurb: 'Warm sand satin. Khaki’s softer cousin.',
    category: 'essentials',
    color: '#d4c4a4',
    finish: 'satin',
    metalness: 0.16,
    roughness: 0.44,
    film: 'Inozetek Satin Sand',
    filmMultiplier: 1.12,
  },
  {
    id: 'racing',
    name: 'Racing Green',
    blurb: 'British racing green gloss. Classic on a new shape.',
    category: 'essentials',
    color: '#0f3a2c',
    finish: 'gloss',
    metalness: 0.2,
    roughness: 0.14,
    film: 'Avery Gloss Dark Green',
    filmMultiplier: 1.16,
  },
  {
    id: 'signal',
    name: 'Signal',
    blurb: 'Warning yellow gloss. Impossible to miss.',
    category: 'graphic',
    color: '#e0b000',
    finish: 'gloss',
    metalness: 0.18,
    roughness: 0.16,
    film: '3M 2080 Gloss Yellow',
    filmMultiplier: 1.18,
  },
  {
    id: 'canyon',
    name: 'Canyon',
    blurb: 'Red earth satin. Desert without the camo.',
    category: 'essentials',
    color: '#7a3a2c',
    finish: 'satin',
    metalness: 0.2,
    roughness: 0.42,
    film: 'Avery Satin Red Earth',
    filmMultiplier: 1.12,
  },
  {
    id: 'slash',
    name: 'Single Slash',
    blurb: 'Dark body, one red stripe. Same graphic on the truck or the Model 3.',
    category: 'graphic',
    color: '#1a1a1c',
    finish: 'gloss',
    lockFinish: true,
    metalness: 0.2,
    roughness: 0.16,
    pattern: 'slash',
    film: 'Printed gloss · A&D',
    filmMultiplier: 1.3,
  },
]

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'hers', label: 'Hers' },
  { id: 'essentials', label: 'Color' },
  { id: 'tactical', label: 'Tactical' },
  { id: 'signature', label: 'Signature' },
  { id: 'graphic', label: 'Graphic' },
  { id: 'oem', label: 'OEM' },
]

export const VEHICLES = [
  { id: 'cybertruck', name: 'Cybertruck', trim: 'AWD Premium' },
  { id: 'model3', name: 'Model 3', trim: 'Standard' },
]

export const COVERAGES = [
  { id: 'full', label: 'Full', hint: 'Every panel' },
  { id: 'twoTone', label: 'Two-tone', hint: 'Hood + roof accent' },
  { id: 'lower', label: 'Lower', hint: 'Rocker line' },
  { id: 'roof', label: 'Roof', hint: 'Top panel' },
]

export const FINISHES = [
  { id: 'satin', label: 'Satin' },
  { id: 'gloss', label: 'Gloss' },
  { id: 'matte', label: 'Matte' },
  { id: 'metallic', label: 'Metallic' },
]

export function getFilm(id) {
  return FILMS.find((f) => f.id === id) ?? FILMS.find((f) => f.id === 'khaki')
}
